# My Playground for Neural Network

In [559]:
from utils import *
from stratified import *
from run import *
from neuralnetwork import *

In [560]:
def importhousedata():
    house = importfile('hw3_house_votes_84.csv', ',')
    housecategory = {}
    for i in house[0]:
        housecategory[i] = 'categorical'
    housecategory["class"] = 'class'
    housedata = np.array(house[1:]).astype(float)
    return housedata, housecategory
def importwinedata():
    wine = importfile('hw3_wine.csv', '\t')
    winecategory = {}
    for i in wine[0]:
        winecategory[i] = 'numerical'
    winecategory["# class"] = 'class'
    winedata = np.array(wine[1:]).astype(float)
    return winedata, winecategory
def importcmcdata():
    cmc = importfile('cmc.data', ',')
    cmccategory = {"Wife's age":"numerical","Wife's education":"categorical",
    "Husband's education":"categorical","Number of children ever born":"numerical",
    "Wife's religion":"binary","Wife's now working?":"binary",
    "Husband's occupation":"categorical","Standard-of-living index":"categorical",
    "Media exposure":"binary","Contraceptive method used":"class"}
    cmcdata = np.array(cmc).astype(int)
    return cmcdata, cmccategory
def importcancerdata():
    cancer = importfile('hw3_cancer.csv', '\t')
    cancercategory = {}
    for i in cancer[0]:
        cancercategory[i] = 'numerical'
    cancercategory["Class"] = 'class'
    cancerdata = np.array(cancer[1:]).astype(float)
    return cancerdata, cancercategory

housedata, housecategory = importhousedata()
winedata, winecategory = importwinedata()
cmcdata,cmccategory = importcmcdata()
cancerdata, cancercategory = importcancerdata()
example_category = {'ece': 'numerical','cs': 'categorical','phy': 'categorical','math': 'categorical','musi': 'categorical','grade': 'class'}
#example_data = np.array([[100,0,1,1,0,0],[123,1,0,1,1,1],[44,1,0,0,0,2],[92,1,0,1,0,3],[73,0,1,0,0,2]])
example_data = np.array([[10,0,1,1,0,0],[23,1,0,1,1,1],[44,1,0,0,0,2],[92,1,0,1,0,3],[73,0,1,0,0,2],[122,0,1,1,0,0],[124,1,0,1,1,1],[44,1,0,0,0,2],[40,1,0,1,0,3],[73,0,1,0,0,2]])

In [561]:
ohe_house_data, ohe_house_category = onehotencoder(housedata, housecategory)
ohe_wine_data, ohe_wine_category = onehotencoder(winedata,winecategory)
ohe_cmc_data, ohe_cmc_category = onehotencoder(cmcdata,cmccategory)
ohe_example_data, ohe_example_category = onehotencoder(example_data,example_category)
ohe_cancer_data, ohe_cancer_category = onehotencoder(cancerdata,cancercategory)

In [562]:
def g(x): # sigmoid function
    return np.exp(x) / (1 + np.exp(x))

In [564]:
# Forward propagation vectorized
def neural_network(normed_hotted_data,ohe_category,weights_list,biasterm=True, minibatchk = 15):
    normed_ohe_copy = normed_hotted_data.copy()
    np.random.shuffle(normed_ohe_copy)
    splitted = np.array_split(normed_ohe_copy, minibatchk)
    
    inputcategory, outputcategory = [],[]
    inputindex, outputindex = [],[]
    n = 0
    for i in ohe_category:
        if ohe_category[i] != 'class_numerical':
            inputcategory.append(i) # name of the input category
            inputindex.append(n) # index of the input category
        else:
            outputcategory.append(i) # name of the output category
            outputindex.append(n) # index of the output category
        n += 1
    
    b = 1 if biasterm else 0
    
    for onebatch in splitted:
        onebatch = onebatch.T
        input_data = onebatch[inputindex].mean(axis=1)
        output_data = onebatch[outputindex].mean(axis=1)
        input_data = np.append(1,input_data) if b == 1 else input_data

        current_layer_a = input_data # input layer is the current layer
        current_layer_index = 0
        for theta in weights_list:
            z = np.dot(theta,current_layer_a)
            a = g(z)
            current_layer_a = np.append(1,a) if (b == 1) and (current_layer_index+1 != len(weights_list)) else a
            current_layer_index += 1
        
        output_predict = current_layer_a # the last attribute is the output for this batch.
        # print(output_predict,'prediction')
        # print(output_data,'real')

    if b==1: ## Place Holder
        c = 1

    return input_data

In [565]:
w = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
indice = [0,1,3]
w = np.array(w)
z = w[indice]
print(z)
input = z.mean(axis=1)
print(input)
input_data = np.append(1,input)
print(input_data)
haihaihai = np.random.rand(5,3) * 2 - 1
print(haihaihai)
nextz = np.dot(haihaihai,input)
print(nextz)

[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]]
[ 2.  5. 11.]
[ 1.  2.  5. 11.]
[[-0.39125814 -0.14376032 -0.07012451]
 [-0.79244761  0.79572367 -0.00916108]
 [ 0.67524909 -0.28848506 -0.21878343]
 [ 0.11429946 -0.89642576 -0.51234574]
 [ 0.34701911  0.80917362  0.97517135]]
[-2.27268752  2.29295121 -2.49854489 -9.88933298 15.46679113]


In [566]:
layerdataparameter = [4,5,4] # [First layer, Second layer, Third layer], not including the bias and input & output layer
initweights = initialize_weights(ohe_house_category,layerdataparameter)
print([len(i) for i in initweights])
kk = neural_network(ohe_house_data,ohe_house_category,initweights)
print(kk)

[4, 5, 4, 2]
[0.54340409 0.36880402] prediction
[0.68965517 0.31034483] real
[0.54308904 0.36944871] prediction
[0.68965517 0.31034483] real
[0.5424336  0.36883964] prediction
[0.65517241 0.34482759] real
[0.54253785 0.36926013] prediction
[0.65517241 0.34482759] real
[0.54412403 0.37088388] prediction
[0.62068966 0.37931034] real
[0.54308518 0.36830733] prediction
[0.55172414 0.44827586] real
[0.54412891 0.36976251] prediction
[0.51724138 0.48275862] real
[0.54363586 0.37010509] prediction
[0.51724138 0.48275862] real
[0.5442517  0.37007393] prediction
[0.5862069 0.4137931] real
[0.54254876 0.36940717] prediction
[0.62068966 0.37931034] real
[0.54315323 0.36858734] prediction
[0.68965517 0.31034483] real
[0.5437934  0.37081499] prediction
[0.55172414 0.44827586] real
[0.54300148 0.36958558] prediction
[0.62068966 0.37931034] real
[0.54201537 0.36904269] prediction
[0.5862069 0.4137931] real
[0.54197355 0.37026334] prediction
[0.65517241 0.34482759] real
[1.         0.03448276 0.448275

In [567]:
k = 5
wok = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12],[13,14],[15,16]])
whaha = len(wok)
print(whaha)
print(wok.shape[0])
random_indices = np.random.choice(whaha, size=k, replace=False)
random_rows = wok[random_indices]
print(random_rows)

8
8
[[ 5  6]
 [ 9 10]
 [11 12]
 [15 16]
 [13 14]]


In [568]:
layernow = 3
layernext = 2
init_weight = np.random.rand(layernext,layernow) * 2 - 1
a_now = np.random.rand(layernow,1)
print(init_weight)
print(a_now)
c = np.dot(init_weight,a_now)
print(c)

[[-0.17417919 -0.6276403   0.29926067]
 [ 0.91724862  0.84413524  0.60472753]]
[[0.86458526]
 [0.02755088]
 [0.31921173]]
[[-0.07235728]
 [ 1.00933243]]
