# My Playground for Neural Network

In [101]:
from utils import *
from stratified import *
from run import *
from neuralnetwork import *

In [102]:
def importhousedata():
    house = importfile('hw3_house_votes_84.csv', ',')
    housecategory = {}
    for i in house[0]:
        housecategory[i] = 'categorical'
    housecategory["class"] = 'class'
    housedata = np.array(house[1:]).astype(float)
    return housedata, housecategory
def importwinedata():
    wine = importfile('hw3_wine.csv', '\t')
    winecategory = {}
    for i in wine[0]:
        winecategory[i] = 'numerical'
    winecategory["# class"] = 'class'
    winedata = np.array(wine[1:]).astype(float)
    return winedata, winecategory
def importcmcdata():
    cmc = importfile('cmc.data', ',')
    cmccategory = {"Wife's age":"numerical","Wife's education":"categorical",
    "Husband's education":"categorical","Number of children ever born":"numerical",
    "Wife's religion":"binary","Wife's now working?":"binary",
    "Husband's occupation":"categorical","Standard-of-living index":"categorical",
    "Media exposure":"binary","Contraceptive method used":"class"}
    cmcdata = np.array(cmc).astype(int)
    return cmcdata, cmccategory
def importcancerdata():
    cancer = importfile('hw3_cancer.csv', '\t')
    cancercategory = {}
    for i in cancer[0]:
        cancercategory[i] = 'numerical'
    cancercategory["Class"] = 'class'
    cancerdata = np.array(cancer[1:]).astype(float)
    return cancerdata, cancercategory

housedata, housecategory = importhousedata()
winedata, winecategory = importwinedata()
cmcdata,cmccategory = importcmcdata()
cancerdata, cancercategory = importcancerdata()
example_category = {'ece': 'numerical','cs': 'categorical','phy': 'categorical','math': 'categorical','musi': 'categorical','grade': 'class'}
#example_data = np.array([[100,0,1,1,0,0],[123,1,0,1,1,1],[44,1,0,0,0,2],[92,1,0,1,0,3],[73,0,1,0,0,2]])
example_data = np.array([[10,0,1,1,0,0],[23,1,0,1,1,1],[44,1,0,0,0,2],[92,1,0,1,0,3],[73,0,1,0,0,2],[122,0,1,1,0,0],[124,1,0,1,1,1],[44,1,0,0,0,2],[40,1,0,1,0,3],[73,0,1,0,0,2]])

In [103]:
ohe_house_data, ohe_house_category = onehotencoder(housedata, housecategory)
ohe_wine_data, ohe_wine_category = onehotencoder(winedata,winecategory)
ohe_cmc_data, ohe_cmc_category = onehotencoder(cmcdata,cmccategory)
ohe_example_data, ohe_example_category = onehotencoder(example_data,example_category)
ohe_cancer_data, ohe_cancer_category = onehotencoder(cancerdata,cancercategory)

In [104]:
def g(x): # sigmoid function
    return np.exp(x) / (1 + np.exp(x))

In [105]:
def costfunction(predict_output, actual_output):
    J = 0
    for i in range(len(predict_output)):
        pass
    return    

In [106]:
# Forward propagation vectorized
def neural_network(normed_hotted_data,ohe_category,weights_list,biasterm=True, minibatchk = 15):
    normed_ohe_copy = normed_hotted_data.copy()
    np.random.shuffle(normed_ohe_copy)
    splitted = np.array_split(normed_ohe_copy, minibatchk)
    
    inputcategory, outputcategory = [],[]
    inputindex, outputindex = [],[]
    n = 0
    for i in ohe_category:
        if ohe_category[i] != 'class_numerical':
            inputcategory.append(i) # name of the input category
            inputindex.append(n) # index of the input category
        else:
            outputcategory.append(i) # name of the output category
            outputindex.append(n) # index of the output category
        n += 1
    
    b = 1 if biasterm else 0
    
    for onebatch in splitted:
        onebatch = onebatch.T
        input_data = onebatch[inputindex].T
        output_data = onebatch[outputindex].T
        # input_data_mean = onebatch[inputindex].mean(axis=1)
        output_data = onebatch[outputindex].T

        # forward propagation
        instance_index = 0

        for one_instance in input_data:
            one_instance = np.append(1,one_instance) if b == 1 else one_instance
            current_layer_a = one_instance # input layer is the current layer
            current_layer_index = 0
            output_real = output_data[instance_index]

            for theta in weights_list:
                z = np.dot(theta,current_layer_a)
                a = g(z)
                current_layer_a = np.append(1,a) if (b == 1) and (current_layer_index+1 != len(weights_list)) else a
                current_layer_index += 1

            output_predict = current_layer_a # the last attribute is the output for this batch.
            instance_index += 1
            

    if b==1: ## Place Holder
        c = 1

    return input_data

In [108]:
layerdataparameter = [4,5,4] # [First layer, Second layer, Third layer], not including the bias and input & output layer
initweights = initialize_weights(ohe_house_category,layerdataparameter)
print([len(i) for i in initweights])
kk = neural_network(ohe_house_data,ohe_house_category,initweights)
# print(kk)

[4, 5, 4, 2]
[0.06896552 0.51724138 0.4137931  0.13793103 0.51724138 0.34482759
 0.         0.34482759 0.65517241 0.03448276 0.5862069  0.37931034
 0.03448276 0.55172414 0.4137931  0.03448276 0.4137931  0.55172414
 0.03448276 0.4137931  0.55172414 0.06896552 0.31034483 0.62068966
 0.         0.37931034 0.62068966 0.         0.37931034 0.62068966
 0.06896552 0.65517241 0.27586207 0.10344828 0.55172414 0.34482759
 0.         0.55172414 0.44827586 0.10344828 0.48275862 0.4137931
 0.06896552 0.44827586 0.48275862 0.27586207 0.10344828 0.62068966]
[0.21404942 0.70556585] prediction
[0. 1.] real
[0.21706739 0.70114558] prediction
[1. 0.] real
[0.21530233 0.70281327] prediction
[1. 0.] real
[0.21684249 0.70167141] prediction
[1. 0.] real
[0.21773937 0.70081667] prediction
[1. 0.] real
[0.21393635 0.703601  ] prediction
[0. 1.] real
[0.21541177 0.70295488] prediction
[0. 1.] real
[0.21445039 0.70353703] prediction
[1. 0.] real
[0.21390712 0.70402802] prediction
[1. 0.] real
[0.21303332 0.70488

In [109]:
k = 5
wok = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12],[13,14],[15,16]])
whaha = len(wok)
print(whaha)
print(wok.shape[0])
random_indices = np.random.choice(whaha, size=k, replace=False)
random_rows = wok[random_indices]
print(random_rows)

8
8
[[ 1  2]
 [15 16]
 [ 7  8]
 [11 12]
 [13 14]]


In [110]:
layernow = 3
layernext = 2
init_weight = np.random.rand(layernext,layernow) * 2 - 1
a_now = np.random.rand(layernow,1)
print(init_weight)
print(a_now)
c = np.dot(init_weight,a_now)
print(c)

[[-0.79817632 -0.84234545  0.94371367]
 [-0.55515763  0.71914237  0.23849824]]
[[0.97281691]
 [0.60306162]
 [0.17966771]]
[[-1.11491076]
 [-0.06352913]]
